name: Run Full Application (Backend + Frontend)

on:
  workflow_dispatch:  # Allows manual triggering
  push:  # Triggers on push to main or specified branches
    branches:
      - main

jobs:
  run-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or your required version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or your required Node version

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Frontend Dependencies
        run: |
          cd frontend/alibabarta-frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend/alibabarta-frontend
          npm run build

      - name: Serve Frontend and Run Backend
        run: |
          # Serve frontend using a simple HTTP server for testing (replace with Nginx if needed)
          cd frontend/alibabarta-frontend/build
          python3 -m http.server 3000 &  # Serve frontend on port 3000 in the background

          # Run backend (Uvicorn) on port 8000
          cd ../../../backend
          uvicorn main:app --host 0.0.0.0 --port 8000
