name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Backend and Frontend
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 8000:8000
          - 80:80

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Install PortAudio
      run: sudo apt-get install portaudio19-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Backend Tests
      run: |
        cd backend
        pytest

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Frontend dependencies
      run: |
        cd frontend/alibabarta-frontend
        npm install

    - name: Build Frontend
      run: |
        npm run build

    - name: Deploy
      if: success()
      run: |
        echo "The deploy step would go here, such as using SCP or SSH to move built files to a server."
